export const books = [
  { title: "1 ... d6 Move by Move", author: "Cyrus Lakdawala" },
  { title: "107 Great Chess Battles, 1939-1945", author: "Alexander Alekhine" },
  { title: "200 Open Games", author: "David Bronstein" },
  { title: "303 Tactical Chess Puzzles", author: "Fred Wilson" },
  { title: "606 Puzzles for Chess Nuts", author: "Fred Wilson" },
  { title: "Alekhine's Defence", author: "Nigel Davies" },
  { title: "All the Wrong Moves", author: "Sasha Chapin" },
  { title: "Amateur's Mind", author: "Jeremy Silman" },
  { title: "Art of Attack in Chess", author: "Vladimir Vukovic" },
  { title: "Art of Chess Analysis", author: "Jan Timman" },
  { title: "Art of Chess Analysis", author: "Jan Timman" },
  { title: "Art of Defence in Chess", author: "Lev Polugaevsky" },
  { title: "Art of Defense in Chess", author: "Andrew Soltis" },
  { title: "Art of Positional Play", author: "Samuel Reshevsky" },
  { title: "Art of Sacrifice in Chess", author: "Rudolf Spielmann" },
  { title: "Art of the King's Indian", author: "Eduard Gufeld" },
  { title: "Art of the Middle Game", author: "Paul Keres" },
  { title: "Attacking Manual 1", author: "Jacob Aagaard" },
  { title: "Attacking Repertoire for White", author: "Sam Collins" },
  { title: "Basic Chess Endings", author: "Reuben Fine" },
  { title: "Beating the King's Indian and Grunfeld", author: "Timothy Taylor" },
  { title: "Beating the Open Games", author: "Mihail Marin" },
  { title: "Beating the Petroff", author: "Vassilios Kotronias" },
  { title: "Beating Unusual Chess Openings", author: "Richard Palliser" },
  { title: "Benko Gambit Revealed", author: "Neil McDonald" },
  { title: "Bird's Opening", author: "Timothy Taylor" },
  { title: "Birth of the Chess Queen", author: "Marilyn Yalom" },
  { title: "Blackmar-Diemer Gambit", author: "Christopher Scheerer" },
  { title: "Bobby Fischer", author: "Karsten Mueller" },
  {
    title:
      "Bobby Fischer Goes to War: How the Soviets Lost the Most Extraordinary Chess Match of All Time",
    author: "David Edmonds",
  },
  { title: "Bobby Fischer: Profile of a Prodigy", author: "Frank Brady" },
  { title: "Botvinnik Semi-Slav", author: "Steffen Pedersen" },
  { title: "Bronstein on the King's Indian", author: "David Bronstein" },
  { title: "Build Up Your Chess 1: The Fundamentals", author: "Artur Yusupov" },
  { title: "Capablanca's Best Chess Endings", author: "Irving Chernev" },
  {
    title: "Caro Kann Defence: Advance Variation and Gambit System",
    author: "Anatoly Karpov",
  },
  { title: "Caro-Kann Defence", author: "Anatoly Karpov" },
  { title: "Checkmate in Prague", author: "Luděk Pachman" },
  { title: "Checkmate!: My First Chess Book", author: "Garry Kasparov" },
  { title: "Chess", author: "László Polgár" },
  { title: "Chess Artist", author: "J. C. Hallman" },
  { title: "Chess Brilliancy", author: "Iakov Damsky" },
  { title: "Chess Duels with the Champions", author: "Yasser Seirawan" },
  { title: "Chess Exam and Training Guide", author: "Igor Khmelnitsky" },
  { title: "Chess Explained: The c3 Sicilian", author: "Sam Collins" },
  { title: "Chess for Zebras", author: "Jonathan Rowson" },
  { title: "Chess from Morphy to Botwinnik", author: "Imre Konig" },
  { title: "Chess Fundamentals", author: "José R. Capablanca" },
  {
    title: "Chess Fundamentals (Revised and Updated)",
    author: "Jose Capablanca",
  },
  { title: "Chess Lessons", author: "Vladimir Popov" },
  { title: "Chess Openings for the Average Player", author: "T. D. Harding" },
  { title: "Chess Openings: Traps And Zaps", author: "Bruce Pandolfini" },
  { title: "Chess Player's Handbook", author: "Howard Staunton" },
  { title: "Chess Self-Improvement", author: "Zenon Franco" },
  { title: "Chess Software User's Guide", author: "Byron Jacobs" },
  { title: "Chess Strategy", author: "Eduard Gufeld" },
  { title: "Chess Strategy in Action", author: "John Watson" },
  {
    title: "Chess Success: Planning After the Opening",
    author: "Neil McDonald",
  },
  {
    title: "Chess World Title Contenders and Their Styles",
    author: "Craig Pritchett",
  },
  { title: "Chessercizes", author: "Bruce Pandolfini" },
  {
    title: "Chigorin Defence According to Morozevich",
    author: "Alexander Morozevich",
  },
  {
    title: "Closed Spanish: Karpov/Zaitsev Systems",
    author: "Anatoly Bikhovsky",
  },
  { title: "Complete Benoni", author: "Lev Psakhis" },
  { title: "Complete Chess Workout", author: "Richard Palliser" },
  { title: "Complete Hedgehog: Volume 1", author: "Sergey Shipov" },
  { title: "Complete Semi-Slav", author: "Peter Wells" },
  { title: "Controversial Samisch King's Indian", author: "Chris Ward" },
  { title: "Counter Gambits", author: "T. D. Harding" },
  { title: "Counterplay", author: "Prof. Robert R. Desjarlais" },
  { title: "Creative Chess Opening Preparation", author: "Viacheslav Eingorn" },
  { title: "Creative Chess Strategy", author: "Alfonso Romero" },
  { title: "Curacao 1962", author: "Jan Timman" },
  { title: "Danger in Chess", author: "Amatzia Avni" },
  { title: "Dangerous Weapons - 1 e4 e5", author: "John Emms" },
  { title: "Dangerous Weapons - The Benoni and Benko", author: "John Emms" },
  { title: "Dangerous Weapons: The Dutch", author: "Richard Palliser" },
  { title: "Dangerous Weapons: The Nimzo-Indian", author: "John Emms" },
  { title: "Dangerous Weapons: The Sicilian", author: "John Emms" },
  { title: "Dealing with d4 Deviations", author: "John Cox" },
  { title: "Decision-Making at the Chessboard", author: "Viacheslav Eingorn" },
  { title: "Decisive Games in Chess History", author: "Ludek Pachman" },
  { title: "Dismantling the Sicilian", author: "Jesus de la Villa" },
  { title: "Dutch Leningrad", author: "Neil McDonald" },
  { title: "Dutch Stonewall", author: "Jacob Aagaard" },
  { title: "Dvoretsky's Analytical Manual", author: "Mark Dvoretsky" },
  { title: "Dvoretsky's Endgame Manual", author: "Mark Dvoretsky" },
  { title: "Dynamic Pawn Play in Chess", author: "Drazen Marovic" },
  { title: "Dynamic Reti", author: "Nigel Davies" },
  {
    title: "Easy Guide to the Panov-Botvinnik Attack",
    author: "Jacob Aagaard",
  },
  { title: "End Game", author: "Dominic Lawson" },
  { title: "Endgame Challenge", author: "John Nunn" },
  { title: "Engaging Pieces", author: "Howard Goldowsky" },
  { title: "English ...e5", author: "Alex Raetsky" },
  { title: "English Attack", author: "Nick de Firmian" },
  { title: "Excelling at Combinational Play", author: "Jacob Aagaard" },
  { title: "Excelling at Positional Chess", author: "Jacob Aagaard" },
  { title: "Excelling at Technical Chess", author: "Jacob Aagaard" },
  { title: "Experts Vs. the Sicilian", author: "Jacob Aagaard" },
  { title: "Fianchetto Grunfeld", author: "Adrian Mikhalchishin" },
  {
    title: "Fifteen Games and Their Stories",
    author: "Michail Moiseevič Botvinnik",
  },
  { title: "Find the Checkmate", author: "Gary Lane" },
  { title: "Find the Winning Move", author: "Gary Lane" },
  { title: "Fire on Board", author: "Alexei Shirov" },
  { title: "Fire on Board Part 2: 1997-2004", author: "Alexei Shirov" },
  { title: "Fischer v. Spassky: Reykjavik 1972", author: "C.H.O'D. Alexander" },
  {
    title: "Fischer Vs. Spassky World Chess Championship Match 1972",
    author: "Svetozar Gligoric",
  },
  { title: "Flank Openings", author: "Richard Palliser" },
  { title: "French Classical", author: "Byron Jacobs" },
  {
    title: "French Defence Advance Variation Volume 1",
    author: "Evgenny Sveshnikov",
  },
  {
    title: "French Defence Advance Variation Volume 2",
    author: "Evgeny Sveshnikov",
  },
  {
    title: "French Defence: Steinitz, Classical and Other Variations",
    author: "Lev Psakhis",
  },
  { title: "French Tarrasch", author: "John Emms" },
  { title: "From London to Elista", author: "Evgeny Bareev" },

  { title: "Fundamental Chess Endings", author: "Frank Lamprecht" },
  { title: "Gambit Guide to the Bogo-Indian", author: "Steffen Pedersen" },
  { title: "Gambit Play", author: "Angus Dunnington" },
  { title: "Gambiteer I", author: "Nigel Davies" },
  { title: "Game of Chess", author: "Siegbert Tarrasch" },
  {
    title:
      "Garry Kasparov on Fischer: Garry Kasparov On My Great Predecessors, Part 4",
    author: "Garry Kasparov",
  },
  {
    title: "Garry Kasparov on Garry Kasparov, Part 1",
    author: "Garry Kasparov",
  },
  {
    title:
      "Garry Kasparov on Modern Chess: Part Two: Kasparov Vs Karpov 1975-1985",
    author: "Garry Kasparov",
  },
  {
    title: "Garry Kasparov on My Great Predecessors",
    author: "Garry Kasparov",
  },
  {
    title: "Garry Kasparov on My Great Predecessors, Part One",
    author: "Garry Kasparov",
  },
  {
    title: "Garry Kasparov on My Great Predecessors, Part Two",
    author: "Garry Kasparov",
  },
  {
    title: "Garry Kasparov's Greatest Chess Games: Vol 1",
    author: "Igor Stohl",
  },
  {
    title: "Garry Kasparov's Greatest Chess Games: Volum 2",
    author: "Igor Stohl",
  },
  { title: "Genius in the Background", author: "Tibor Karolyi" },
  { title: "Grandmaster Versus Amateur", author: "Jacob Aagaard" },
  { title: "Great Moments in Modern Chess", author: "Reuben Fine" },
  { title: "Greatest Ever Chess Opening Ideas", author: "Christoph Scheerer" },
  { title: "Grunfeld Defence", author: "Nigel Davies" },
  { title: "Hedgehog", author: "Mihai Suba" },
  { title: "Heroic Tales", author: "Taylor Kingston (Editor)" },
  { title: "Hippopotamus Rises", author: "Andrew Martin" },
  { title: "How Chess Games Are Won and Lost", author: "Lars Bo Hansen" },
  { title: "How Karpov Wins", author: "Edmar Mednis" },
  { title: "How to Beat Bobby Fischer", author: "Edmar Mednis" },
  { title: "How to Beat Your Dad at Chess", author: "Murray Chandler" },
  { title: "How to Defend in Chess", author: "Colin Crouch" },
  { title: "How to Play Chess Endgames", author: "Karsten Muller" },
  { title: "How to Play the English Opening", author: "Anatoly Karpov" },
  { title: "How to Play the Middle Game in Chess", author: "John Littlewood" },
  { title: "How to Reassess Your Chess", author: "Jeremy Silman" },
  { title: "How To Reassess Your Chess", author: "Jeremy Silman" },
  {
    title: "How to Win in the Chess Endings",
    author: "Israel Albert Horowitz",
  },
  { title: "Imagination in Chess", author: "Paata Gaprindashvili" },
  { title: "Immortal Game", author: "David Shenk" },
  { title: "Improve Your Chess", author: "Lars Bo Hansen" },
  {
    title: "Inner Game of Chess: How to Calculate and Win",
    author: "Andrew Soltis",
  },
  { title: "Inside the Chess Mind", author: "Jacob Aagaard" },
  { title: "Italian Game and Evans Gambit", author: "Jan Pinski" },
  {
    title: "Kasparov: How His Predecessors Misled Him About Chess",
    author: "Tibor Karolyi",
  },
  {
    title: "Kasparov: How His Predecessors Misled Him About Chess",
    author: "Tibor Karolyi",
  },
  { title: "Kasparov vs Karpov 1986-1987", author: "Garry Kasparov" },
  { title: "Kasparov vs. Karpov 1990", author: "Garry Kasparov" },
  { title: "Kasparov's Fighting Chess 1993-1998", author: "Tibor Karolyi" },
  { title: "Kasparov's Fighting Chess 1999-2005", author: "Tibor Karolyi" },
  { title: "Key Elements of Chess Strategy", author: "Georgy Lisitsin" },
  { title: "Khalifman", author: "Gennady Nesis" },
  { title: "King Power in Chess", author: "Edmar Mednis" },
  { title: "King's Gambit", author: "Paul Hoffman" },
  { title: "King's Gambit", author: "Neil McDonald" },
  {
    title: "King's Indian Defence: Mar Del Plata Variation",
    author: "Svetozar Gligoric",
  },
  { title: "Kings, Commoners and Knaves", author: "Edward Winter" },
  { title: "Kings of New York", author: "Michael Weinreb" },
  { title: "Kramnik", author: "Vladimir Kramnik" },
  { title: "Lasker's Manual of Chess", author: "Emanuel Lasker" },
  { title: "Learn from the Legends", author: "Mihail Marin" },
  { title: "Lessons in Chess Strategy", author: "Valeri Beim" },
  { title: "Mammoth Book of Chess 2022 Edition", author: "Graham Burgess" },
  {
    title: "Mammoth Book of the World's Greatest Chess Games",
    author: "Graham Burgess",
  },
  { title: "Master Pieces", author: "Gareth Williams" },
  { title: "Mastering Positional Chess", author: "Daniel Naroditsky" },
  { title: "Mastering the Chess Openings Volume 2", author: "John Watson" },
  { title: "Mastering the Chess Openings Volume 3", author: "John Watson" },
  { title: "Mastering the Chess Openings: Volume 4", author: "John Watson" },
  { title: "Mastering the Sicilian", author: "Danny Kopec" },
  { title: "Meran Semi-Slav", author: "Reinaldo Vera" },
  { title: "Middle Game in Chess", author: "Eugene A. Znosko-Borovsky" },
  { title: "Middlegame in Chess", author: "Reuben Fine" },
  { title: "Modern Benoni Revealed", author: "Richard Palliser" },
  { title: "Modern Chess Analysis", author: "Robin Smith" },
  { title: "Modern Chess - Move by Move", author: "Colín Crouch" },
  { title: "Modern Chess Openings, 15th Edition", author: "Nick De Firmian" },
  { title: "Morphy's Games of Chess", author: "Philip Sergeant" },
  { title: "Most Amazing Chess Moves of All Time", author: "John Emms" },
  {
    title: "Most Instructive Games of Chess Ever Played",
    author: "Irving Chernev",
  },
  { title: "My 60 Memorable Games", author: "Bobby Fischer" },
  { title: "My Best Games of Chess, 1908-1937", author: "Alexander Alekhine" },
  { title: "My Best Games of Chess: 1935-1957", author: "Smyslov" },
  {
    title: "My Best Games: Volume 1, Games with White",
    author: "Victor Korchnoi",
  },
  {
    title: "My Best Games: Volume 2, Games with Black",
    author: "Victor Korchnoi",
  },
  { title: "My Magic Years with Topalov", author: "Romain Edouard" },
  { title: "My System", author: "Aaron Nimzowitsch" },
  { title: "My System", author: "Aron Nimzowitsch" },
  { title: "Najdorf - Life and Games", author: "Thomas Lissowski" },
  { title: "Nimzo-Indian", author: "Reinaldo Vera" },
  { title: "Nimzo-Indian Rubinstein", author: "Dunnington" },
  { title: "Open Sicilian 1", author: "Milos Pavlovic" },
  {
    title: "Opening for White According to Anand: 1.e4 Volume 2",
    author: "Alexander Khalifman",
  },
  {
    title: "Pal Benko: My Life, Games and Compositions",
    author: "Jeremy Silman",
  },
  { title: "Paul Keres", author: "Paul Keres" },
  { title: "Paul Keres", author: "Paul Keres" },
  { title: "Pawn Power in Chess", author: "Hans Kmoch" },
  { title: "Pawn Sacrifice!", author: "Timothy Taylor" },
  { title: "Pawn Structure Chess", author: "Andrew Soltis" },
  { title: "Petroff Defence", author: "Alex Raetsky" },
  { title: "Philidor Files", author: "Christian Bauer" },
  { title: "Pirc in Black and White", author: "James Vigus" },
  { title: "Play 1... b6", author: "Christian Bauer" },
  { title: "Play 1... Nc6!", author: "Christoph Wisnewski" },
  { title: "Play e4 e5!", author: "Nigel Davies" },
  { title: "Play the Benko Gambit", author: "Nicolai V. Pedersen" },
  { title: "Play the French", author: "John L. Watson" },
  { title: "Play the King's Indian", author: "Joe Gallagher" },
  { title: "Play the Nimzo-Indian", author: "Edward Dearing" },
  { title: "Play the Ponziani", author: "Dave Taylor" },
  { title: "Play the Ruy Lopez", author: "Andrew Greet" },
  { title: "Positional Chess Handbook", author: "Israel Gelfer" },
  { title: "Positional Play", author: "Mark Dvoretsky" },
  { title: "Practical Chess Defence", author: "Jacob Aagaard" },
  { title: "Practical Chess Endings by Keres", author: "Paul Keres" },
  { title: "Practical Chess Psychology", author: "Amatzia Avni" },
  {
    title: "Practical Endgame Play - Mastering the Basics",
    author: "Efstratios Grivas",
  },
  { title: "Queen of Katwe", author: "Tim Crothers" },
  { title: "Queen's Gambit Accepted", author: "Chris Ward" },
  { title: "Queen's Gambit Declined", author: "Bogdan Lalic" },
  { title: "Queen's Gambit Declined: 5 Bf4!", author: "Colin Crouch" },
  { title: "Queen's Indian", author: "Peter Wells" },
  { title: "Questions of Modern Chess Theory", author: "Isaac Lipnitsky" },
  { title: "Reassess Your Chess Workbook", author: "Jeremy Silman" },
  { title: "Rethinking the Chess Pieces", author: "Andrew Soltis" },
  { title: "Revolution in the 70's", author: "Garry Kasparov" },
  { title: "Road to Chess Improvement", author: "Alex Yermolinsky" },
  { title: "Rocking the Ramparts", author: "Larry Christiansen" },
  { title: "Rubinstein's Chess Masterpieces", author: "Akiba Rubinstein" },
  { title: "Ruy Lopez", author: "Neil McDonald" },
  { title: "Samisch King's Indian Uncovered", author: "Alexander Cherniaev" },
  { title: "Scotch Game EXplained", author: "Gary Lane" },
  { title: "Secrets of Chess Defence", author: "Mihail Marin" },
  { title: "Secrets of Chess Transformations", author: "Drazen Marovic" },
  { title: "Secrets of Modern Chess Strategy", author: "John Watson" },
  { title: "Secrets of Positional Chess", author: "Marovic Drazen" },
  { title: "Secrets of Practical Chess", author: "John Nunn" },
  { title: "Secrets of Practical Chess", author: "John Nunn" },
  { title: "Seven Deadly Chess Sins", author: "Jonathan Rowson" },
  { title: "Sicilian Defense", author: "Gennadi Timoshchenko" },
  { title: "Silman's Complete Endgame Couorse", author: "Jeremy Silman" },
  { title: "Simple Chess", author: "Michael Stean" },
  { title: "Sniper", author: "Charlie Storey" },
  { title: "Sokolov's Best Games", author: "Ivan Sokolov" },
  { title: "Solitaire Chess", author: "Bruce Pandolfini" },
  { title: "Sorcerer's Apprentice", author: "Tom Furstenberg" },
  { title: "Soviet Chess School", author: "Alexander Kotov" },
  { title: "Soviet Chess Strategy", author: "Alexey Suetin" },
  { title: "Spanish Exchange Variation", author: "Stefan Kindermann" },
  { title: "Starting Out: Benoni Systems", author: "Alexander Raetsky" },
  { title: "Starting Out: Closed Sicilian", author: "Richard Palliser" },
  { title: "Starting Out: King's Indian Attack", author: "John Emms" },
  { title: "Starting Out: Modern Benoni", author: "Endre Vegh" },
  { title: "Starting Out: Queen's Indian", author: "John Emms" },
  { title: "Starting Out: Sicilian Najdorf", author: "Richard Palliser" },
  { title: "Starting Out: Sicilian Sveshnikov", author: "John Cox" },
  { title: "Starting Out: Slav and Semi-Slav", author: "Glenn Flear" },
  { title: "Starting Out - The Accelerated Dragon", author: "Andrew Greet" },
  { title: "Starting Out: The Caro-Kann", author: "Joe Gallagher" },
  { title: "Starting Out: The Colle", author: "Richard Palliser" },
  { title: "Starting Out: The Dutch Defence", author: "Richard Palliser" },
  { title: "Starting Out: The English", author: "Neil McDonald" },
  { title: "Starting Out: The Grunfeld", author: "Jacob Aagaard" },
  { title: "Starting Out: The King's Indian", author: "Joe Gallagher" },
  { title: "Starting Out: The Nimzo-Indian", author: "Chris Ward" },
  { title: "Starting Out: The Pirc/Modern", author: "Joe Gallagher" },
  { title: "Starting Out: The Reti", author: "Neil McDonald" },
  { title: "Starting Out: The Scotch Game", author: "John Emms" },
  { title: "Starting Out: The Sicilian", author: "John Emms" },
  { title: "Strategic Chess", author: "Edmar Mednis" },
  { title: "Survival Guide to Competitive Chess", author: "John Emms" },
  { title: "Tactical Chess Endings", author: "John Nunn" },
  { title: "Taimanov's Selected Games", author: "Mark Taimanov" },
  { title: "Tango! A Dynamic Answer to 1. d4", author: "Richard Palliser" },
  { title: "Technique in Chess", author: "Gerald Abrahams" },
  { title: "Test of Time", author: "Garry Kasparov" },
  { title: "Test Your Chess with Daniel King", author: "Daniel King" },
  { title: "Think Like a Grandmaster", author: "A.A. Kotov" },
  { title: "Training for the Tournament Player", author: "Mark Dvoretsky" },
  { title: "Transpo Tricks in Chess", author: "Andrew Soltis" },
  {
    title:
      "Turk: The Life and Times of the Famous 18th Century Chess Playing Machine",
    author: "Tom Standage",
  },
  { title: "Turning Advantage Into Victory in Chess", author: "Andrew Soltis" },
  { title: "Ultimate Colle", author: "Gary Lane" },
  { title: "Uncompromising Chess", author: "Alexander Belyavsky" },
  { title: "Understanding Chess Move by Move", author: "John Nunn" },
  { title: "Understanding Chess Tactics", author: "Martin Weteschnik" },
  { title: "Understanding Maroczy Structures", author: "Adrian Mikhalchishin" },
  { title: "Understanding the Grünfeld", author: "Jonathan Rowson" },
  { title: "Understanding the King's Indian", author: "Mikhail Golubev" },
  { title: "Understanding the Leningrad Dutch", author: "Valeri Beim" },
  { title: "Van Perlo's Endgame Tactics", author: "Ger van Perlo" },
  {
    title: "Vishy Anand - My Best Games of Chess",
    author: "Viswanathan Anand",
  },
  { title: "Why Lasker Matters", author: "Andrew Soltis" },
  { title: "Why You Lose at Chess", author: "Tim Harding" },
  { title: "Win with the Stonewall Dutch", author: "Sverre Johnsen" },
  { title: "Winning Chess Endings", author: "Yasser Seirawan" },
  { title: "Winning Chess Strategies", author: "Yassser Seirawan" },
  { title: "Winning Chess Tactics", author: "Yasser Seirawan" },
  { title: "Winning Endgame Technique", author: "Alexander Beliavsky" },
  { title: "Winning Pawn Structures", author: "Alexander Baburin" },
  { title: "Winning with Chess Psychology", author: "Pal Benko" },
  { title: "Winning with the Trompowsky", author: "Peter Wells" },
  { title: "Wisest Things Ever Said About Chess", author: "Andrew Soltis" },
  {
    title: "Zuke 'em the Colle-Zukertort Revolutionized",
    author: "David Rudel",
  },
];
